#! /usr/bin/env node
// vim: set filetype=javascript
var fs = require('fs');
var sys = require('sys');


var main = function () {
  var fileName;
  if (process.argv[2]) {
    fileName = process.argv[2].toString();
  }
  if (fileName === undefined) {
    sys.puts("USAGE: "+process.argv[1].split('/').reverse()[0]+" <FileName>");
  } else if (fileName === "-") {
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', function(data) {
      process.stdout.write(prettyJson(data));
    });
  } else {
    var input = fs.readFileSync(fileName).toString();
    sys.puts(prettyJson(input));
  }
}

var prettyJson = function(input) {
  var json = JSON.parse(input);
  return JSON.stringify(json, null, 2);
}

main();
